#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source Z | https://github.com/rupa/z/wiki
source ~/z.sh

# Source IStio auto-completion | https://istio.io/docs/ops/diagnostic-tools/istioctl/#enabling-auto-completion
source ~/_istioctl

# Needed for tmux solarized theme
if [[ -n ${TMUX} ]]; then
  export TERM="screen-256color"
else
  export TERM="xterm-256color"
fi

# Docker completion
# Ref: https://docs.docker.com/compose/completion/#zsh
fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit -i

# Override default editor (nano)
export EDITOR='vim'

# GO LANG
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/.go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# VSCode
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Idea
export PATH="$PATH:/Users/justinvangrootveld/idea"

# Needed for tmuxp
export DISABLE_AUTO_TITLE='true'

# Aliasses
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias sublime="open -a /Applications/Sublime\ Text.app"

# Git
alias fetch="git fetch"
alias pull="git pull"

# Kubernetes
alias k='kubectl'
alias kg='kubectl get'
alias kgpo='kubectl get pod'
alias kd='kubectl describe'


# Tmuxp Completion
# eval "$(_TMUXP_COMPLETE=source tmuxp)"
# autoload bashcompinit
# bashcompinit

# Java version switch
export JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
#export JAVA_11_HOME=$(/usr/libexec/java_home -v11)
export JAVA_13_HOME=$(/usr/libexec/java_home -v13)

# Define aliases for easy java version switching
alias java8='export JAVA_HOME=$JAVA_8_HOME'
#alias java11='export JAVA_HOME=$JAVA_11_HOME'
alias java13='export JAVA_HOME=$JAVA_13_HOME'

# Default java13
java13
