-- set the path to these installation; if you previously installed via the now deprecated :LspInstall, use
-- local root_path = "/Users/justinvangrootveld/third_party/lua-language-server"
-- local binary = root_path.."/bin/macOS/lua-language-server"

-- require'lspconfig'.gopls.setup {
--     cmd = {binary, "-E", root_path .. "/main.lua"};
--     settings = {
--         gopls = {
--             analyses = {
--                 unusedparams = true,
--             },
--             staticcheck = true,
--         },
--     },
--     on_attach = require'completion'.on_attach
-- }
